### ISSUE TITLE
ERROR: gpuview does't show anything when GPU does not support processes monitoring

### ISSUE THREAD

**Issue by Daigo-Kanda** [fgaim/gpuview#3]
In the list of GPU information sent from gpustat, if processes is not supported, an exception will be raised and an error will occur. In that case, nothing will be displayed in the dashboard.

**Comment by ZuoxiangWang** [comment]
why tee: /etc/supervisor/conf.d/gpuview.conf: No such file or directory

**Comment by Daigo-Kanda** [comment]
Did you run gpuview as a service?

**Comment by ZuoxiangWang** [comment]
Yes, I deployed eight services and six of them were fine, but two of them had problems and ended up with 22 Gpus on the dashboard, but those two had errors and I had to give up run gpuview as a service.can only gpuview run to show the dashboard

**Comment by Daigo-Kanda** [comment]
Please indicate the environment in which you ran gpuview.
Also show us what errors you got.

This is already a closed issue.
If there are new errors, you should open a new issue.
